version: "3.8"

services:
  # Neo4j Database
  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - "7474:7474" # HTTP (Browser access)
      - "7687:7687" # Bolt (Driver connection)
    environment:
      - NEO4J_AUTH=neo4j/test1234
    volumes:
      - neo4j_data:/data

  # FastAPI Application
  api:
    build:
      context: .             # where your Dockerfile is (root of project)
      dockerfile: Dockerfile # name of your Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"          # expose FastAPI
    depends_on:
      - neo4j                # wait for neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=test1234
    volumes:
      - .:/app               # optional: live reload in dev mode

volumes:
  neo4j_data:
